[package]
name = "otto"
version = "0.1.0"
edition = "2021"
default-run = "otto"

[[bin]]
name = "otto"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
time = { version = "0.3", features = ["formatting", "parsing", "macros"] }
fs4 = { version = "0.9", features = ["sync"] }
tempfile = "3"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 2
